In [280]:
import numpy as np
import pandas as pd
import csv

In [281]:
train_data= pd.read_csv("twitter_x_y_train.csv")
test_data= pd.read_csv("twitter_x_test.csv")

train=train_data.copy()
test=test_data.copy()
train.shape

(10980, 12)

In [282]:
train

tweet_id airline_sentiment     airline  \
0      567900433542488064          negative   Southwest   
1      569989168903819264          positive   Southwest   
2      568089179520954368          positive      United   
3      568928195581513728          negative   Southwest   
4      568594180014014464          negative      United   
...                   ...               ...         ...   
10975  569934458364813313           neutral    American   
10976  568564006329434113          positive      United   
10977  569643648910028801          negative  US Airways   
10978  568864981917110272          negative  US Airways   
10979  568929299350179840          negative      United   

      airline_sentiment_gold           name negativereason_gold  \
0                        NaN  ColeyGirouard                 NaN   
1                        NaN  WalterFaddoul                 NaN   
2                        NaN      LocalKyle                 NaN   
3                        NaN    amccarthy19                 NaN   
4                        NaN        J_Okayy                 NaN   
...                      ...            ...                 ...   
10975                    NaN  Cottopanama85                 NaN   
10976                    NaN   PaulBEsteves                 NaN   
10977                    NaN    runfixsteve                 NaN   
10978                    NaN     CLChicosky                 NaN   
10979                    NaN     JW_Blocker                 NaN   

       retweet_count                                               text  \
0                  0  @SouthwestAir I am scheduled for the morning, ...   
1                  0  @SouthwestAir seeing your workers time in and ...   
2                  0  @united Flew ORD to Miami and back and  had gr...   
3                  0     @SouthwestAir @dultch97 that's horse radish 😤🐴   
4                  0  @united so our flight into ORD was delayed bec...   
...              ...                                                ...   
10975              0                            @AmericanAir followback   
10976              0  @united thanks for the help. Wish the phone re...   
10977              0  @usairways the. Worst. Ever. #dca #customerser...   
10978              0  @nrhodes85: look! Another apology. DO NOT FLY ...   
10979              1  @united you are by far the worst airline. 4 pl...   

      tweet_coord              tweet_created              tweet_location  \
0             NaN  2015-02-17 20:16:29 -0800             Washington D.C.   
1             NaN  2015-02-23 14:36:22 -0800  Indianapolis, Indiana; USA   
2             NaN  2015-02-18 08:46:29 -0800                    Illinois   
3             NaN  2015-02-20 16:20:26 -0800                         NaN   
4             NaN  2015-02-19 18:13:11 -0800                         NaN   
...           ...                        ...                         ...   
10975         NaN  2015-02-23 10:58:58 -0800                 ohio,panama   
10976         NaN  2015-02-19 16:13:17 -0800                    Brooklyn   
10977         NaN  2015-02-22 15:43:24 -0800      St. Augustine, Florida   
10978         NaN  2015-02-20 12:09:15 -0800                         NaN   
10979         NaN  2015-02-20 16:24:49 -0800                         NaN   

                    user_timezone  
0          Atlantic Time (Canada)  
1      Central Time (US & Canada)  
2      Central Time (US & Canada)  
3          Atlantic Time (Canada)  
4      Eastern Time (US & Canada)  
...                           ...  
10975                         NaN  
10976  Eastern Time (US & Canada)  
10977                         NaN  
10978                         NaN  
10979                         NaN  

[10980 rows x 12 columns]

In [283]:
tweets=np.array(train["text"])
sentiment=np.array(train["airline_sentiment"])
sentiment

array(['negative', 'positive', 'positive', ..., 'negative', 'negative',
       'negative'], dtype=object)

## Cleaning of Tweets

In [284]:
import nltk
from nltk.corpus import stopwords
import string

In [285]:
stop=stopwords.words('english')
punc=list(string.punctuation)
stop = punc+stop

In [286]:
from nltk.corpus import wordnet
def get_simple_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    if tag.startswith('V'):
        return wordnet.VERB
    if tag.startswith('N'):
        return wordnet.NOUN
    if tag.startswith('R'):
        return wordnet.ADV
    
    else:
        return wordnet.NOUN

In [287]:
from nltk import pos_tag
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def clean(text):
    words=word_tokenize(text)
    clean_words=[]
    for w in words:
        if w.lower() not in stop:
            pos = pos_tag([w])
            clean_word=lemmatizer.lemmatize(w,pos=get_simple_pos(pos[0][1]))
            clean_words.append(clean_word)
    clean_text= " ".join(clean_words)
    return clean_text
            
            
            
        

In [288]:
tweets = [clean(tweet) for tweet in tweets]
tweets

['SouthwestAir schedule morning 2 day fact yes .. sure even flight one Cancelled Flightled',
 'SouthwestAir see worker time time go beyond love fly guy Thank',
 'united Flew ORD Miami back great crew service leg THANKS',
 "SouthwestAir dultch97 's horse radish 😤🐴",
 'united flight ORD delayed Air Force One last flight SBN 8:20 5 min land',
 'united load u fly sardine knew pilot 2 hour Late Flight incompetent beyond belief',
 "JetBlue stock response Delays frustrate poor cust serv amp told 3 ppl wait amp 'd come back",
 "JetBlue 'd nice Hoping rack enough mile take trip Seattle enjoy perfect latte city coffee",
 'united frankly bad customer service ever Problems happen deal defines company Never United',
 "SouthwestAir yeah haha Never one 's expensive 😂😂 much fun destinationdragons",
 "SouthwestAir MCO- gt DCA flight almost full people screw MSY-DCA Cancelled Flightation united USAirways n't Cancelled Flight SWA=mistake",
 "JetBlue 's easy way get ticket receipt get one check get one on

## Classification

In [289]:
# data=[]
# for i in range(len(tweets)):
#     data.append((tweets[i],sentiment[i]))
# data

In [290]:
# import random
# random.shuffle(data)

In [291]:
# train_data = data[:7000]
# test_data = data[7000:]

# train_tweets = [ tweet for tweet, sent in train_data]
# train_sent = [ sent for tweet, sent in train_data]

# test_tweets = [ tweet for tweet, sent in test_data]
# test_sent = [ sent for tweet, sent in test_data]

In [292]:
from sklearn.model_selection import train_test_split

tweets_train,tweets_test,sent_train,sent_test = train_test_split(tweets,sentiment)

In [293]:

from sklearn.feature_extraction.text import CountVectorizer
count_vec = CountVectorizer(max_features=5000,max_df=0.8,ngram_range = (1,2))

X_train = count_vec.fit_transform(tweets_train)
Y_train = sent_train


### Trying SVC

In [299]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score,KFold,GridSearchCV
clf_1 = SVC(C=10,gamma = 0.01)

clf_1.fit(X_train,Y_train)

SVC(C=10, gamma=0.01)

In [300]:
X_test = count_vec.transform(tweets_test)
Y_test = sent_test

In [303]:
Y_Pred=clf_1.predict(X_test)
clf_1.score(X_test,Y_test)

0.7799635701275045

In [298]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(Y_test,Y_Pred))
print(confusion_matrix(Y_test,Y_Pred))

              precision    recall  f1-score   support

    negative       0.82      0.81      0.81      1737
     neutral       0.48      0.46      0.47       586
    positive       0.57      0.64      0.60       422

    accuracy                           0.71      2745
   macro avg       0.62      0.64      0.63      2745
weighted avg       0.71      0.71      0.71      2745

[[1402  230  105]
 [ 221  270   95]
 [  93   60  269]]


### Trying RandomForest

In [239]:
from sklearn import ensemble
clf_2 = ensemble.RandomForestClassifier()

In [240]:
clf_2.fit(X_train,Y_train)

RandomForestClassifier()

In [241]:
Y_Pred=clf_2.predict(X_test)
clf_2.score(X_test,Y_test)

0.7406193078324226

In [242]:

print(classification_report(Y_test,Y_Pred))
print(confusion_matrix(Y_test,Y_Pred))

              precision    recall  f1-score   support

    negative       0.79      0.88      0.84      1709
     neutral       0.55      0.46      0.50       604
    positive       0.73      0.57      0.64       432

    accuracy                           0.74      2745
   macro avg       0.69      0.64      0.66      2745
weighted avg       0.73      0.74      0.73      2745

[[1510  152   47]
 [ 283  275   46]
 [ 109   75  248]]


### Trying Naive Bayes

In [243]:
from sklearn.naive_bayes import MultinomialNB
clf_3 = MultinomialNB()

In [244]:
clf_3.fit(X_train,Y_train)

MultinomialNB()

In [245]:
Y_Pred=clf_3.predict(X_test)
clf_3.score(X_test,Y_test)

0.760655737704918

In [246]:
print(classification_report(Y_test,Y_Pred))
print(confusion_matrix(Y_test,Y_Pred))

              precision    recall  f1-score   support

    negative       0.82      0.89      0.85      1709
     neutral       0.61      0.48      0.53       604
    positive       0.69      0.66      0.68       432

    accuracy                           0.76      2745
   macro avg       0.70      0.68      0.69      2745
weighted avg       0.75      0.76      0.75      2745

[[1513  131   65]
 [ 254  288   62]
 [  88   57  287]]


## Prediciting

In [312]:

count_vec_1 = CountVectorizer(max_features=2000,max_df=0.8,ngram_range = (1,2))

X = count_vec_1.fit_transform(tweets)
Y = sentiment

In [313]:
clf_f = SVC(C=10, gamma = 0.01)
clf_f.fit(X,Y)

SVC(C=10, gamma=0.01)

In [314]:
test_tweets=np.array(test["text"])

In [315]:
test_tweets = [clean(test_tweet) for test_tweet in test_tweets]
test_tweets

["AmericanAir car gng DFW Pulled 1hr ago icy road On-hold AA since 1hr Ca n't reach arpt AA2450 Wat 2",
 'AmericanAir plane ’ land identical bad condition GRK accord METARs',
 "SouthwestAir ca n't believe many pay customer left high dry reason flight Cancelled Flightlations Monday BDL Wow",
 'USAirways legitimately say would rather driven cross country flown US Airways',
 'AmericanAir still response AA great job guy',
 'united developer fly tmrw morn w/45 min layover earlier flight 1.5hr layover move',
 'USAirways hello Anyone',
 'USAirways husainhaqqani Mr. Husain u shld protest well one ur party member Rehman Malik delayed PIA flight hour ..',
 "USAirways likely flightaware say plane still Durango n't depart",
 "AmericanAir n't even give option hold .. say line busy Plz try Late Flightr",
 'united announcement pre boarding address mobility disability require travel lot stuff preboard',
 'USAirways really embarrass ask complimentary drink/snack detailed http //t.co/9zA6xb1h89 amp argu

In [316]:
X_Test = count_vec_1.transform(test_tweets)
Y_Test = clf_f.predict(X_Test)

In [317]:
Y_Test

array(['negative', 'negative', 'negative', ..., 'negative', 'positive',
       'negative'], dtype=object)

In [318]:
np.savetxt("Y_Pred_Test_Twitter.csv",Y_Test, fmt='%s')